version: "3.8"
services:
  db:
    image: postgres
    container_name: repository_finder_pgdb
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - repository_finder_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: repository_finder_pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - repository_finder_pgadmin-data:/var/lib/pgadmin

volumes:
  repository_finder_pgdata:
  repository_finder_pgadmin-data: